site_name: rsprta/unbound
site_url: "https://radek-sprta.gitlab.io/docker-unbound"
site_author: Radek Sprta
theme: cinder
nav:
  - Home: index.md
  - Contributing: contributing.md
  - License: license.md
repo_url: https://gitlab.com/radek-sprta/docker-unbound
